import logging
import os
import pickle
import threading
from typing import List, Optional, Tuple
from collections import Counter

import faiss
import numpy as np

from api.schemas.classified_schema import ClassifiedSignal
from api.schemas.failure_category_schema import FailureCategory
from api.schemas.log_signal_schema import LogSignal
from api.app.config import settings
from utils.text_normalizer import text_norm_obj
from analyzer.embedding.embedding_service import embedding_obj

logger = logging.getLogger(__name__)

FEEDBACK_BATCH_SIZE = 20


class SemanticClassifier:
    """
    Semantic classifier using OpenAI embeddings, a FAISS flat L2 index and
    incremental k-NN learning.

    On initialisation the classifier attempts to load a pre-trained model from
    disk.  If no model file is found it bootstraps itself from synthetic
    training data generated by
    :mod:`analyzer.classifiers.training.synthetic_data_generator`.
    """

    def __init__(self, model_path: str = "models/semantic.pkl"):
        self._model_path = model_path
        self._index_path = model_path.replace(".pkl", ".faiss")

        self._training_labels: List[FailureCategory] = []
        self.dimension: Optional[int] = None
        self.index: Optional[faiss.Index] = None
        self.k_neighbors: int = 3  # k-NN voting

        # Feedback batching
        self._pending_texts: List[str] = []
        self._pending_labels: List[FailureCategory] = []

        self._lock = threading.Lock()
        self._is_trained = False
        
        self._try_load()

    @property
    def is_trained(self) -> bool:
        return self._is_trained

    def train(
        self,
        labeled_signals: List[Tuple[LogSignal, FailureCategory]],
    ) -> None:
        """
        Train the FAISS index from a list of labelled log signals.

        Existing index contents are replaced on each call.

        Args:
            labeled_signals: Pairs of (LogSignal, FailureCategory) to train on.
        """
        if not labeled_signals:
            return

        texts = [self._extract_text(s) for s, _ in labeled_signals]
        labels = [label for _, label in labeled_signals]

        embeddings = embedding_obj.embed_batch(text=texts)

        with self._lock:
            self.dimension = embeddings.shape[1]
            self.index = faiss.IndexFlatL2(self.dimension)
            self.index.add(embeddings)
            self._training_labels = labels
            self._is_trained = True

        logger.info("SemanticClassifier trained on %d samples.", len(texts))

    def classify(
        self,
        signals: List[LogSignal],
        embeddings: Optional[np.ndarray] = None,
    ) -> List[ClassifiedSignal]:
        """
        Classify a batch of log signals using k-NN on the FAISS index.

        If no trained index is available every signal is returned as UNKNOWN.
        When *embeddings* is provided it must be aligned with *signals* and
        have the same dimensionality as the training index.  Otherwise
        embeddings are generated on-the-fly.

        Args:
            signals:    Signals to classify.
            embeddings: Optional pre-computed embedding matrix.

        Returns:
            List of :class:`ClassifiedSignal` with k-NN-derived categories
            and confidence scores.
        """
        if not self._is_trained or not self.index:
            return [
                ClassifiedSignal(
                    signal=s,
                    best_category=FailureCategory.UNKNOWN,
                    classified_confidence=0.0,
                )
                for s in signals
            ]

        if embeddings is None:
            texts = [self._extract_text(s) for s in signals]
            embeddings = embedding_obj.embed_batch(text=texts)
        else:
            if embeddings.shape[0] != len(signals):
                raise ValueError(
                    f"Embeddings count ({embeddings.shape[0]}) "
                    f"doesn't match signals count ({len(signals)})"
                )
            if embeddings.shape[1] != self.dimension:
                raise ValueError(
                    f"Embedding dimension ({embeddings.shape[1]}) "
                    f"doesn't match trained dimension ({self.dimension})"
                )

        k = min(self.k_neighbors, len(self._training_labels))
        distances, indices = self.index.search(embeddings, k=k)

        results = []
        for i, signal in enumerate(signals):
            neighbor_categories = [
                self._training_labels[idx] for idx in indices[i]
            ]
            neighbor_distances = distances[i]

            category_scores = {}
            for cat, dist in zip(neighbor_categories, neighbor_distances):
                weight = 1.0 / (1.0 + dist)
                category_scores[cat] = category_scores.get(cat, 0.0) + weight

            best_category = max(category_scores.items(), key=lambda x: x[1])[0]

            total_weight = sum(category_scores.values())
            confidence = float(category_scores[best_category] / total_weight)

            results.append(
                ClassifiedSignal(
                    signal=signal,
                    best_category=best_category,
                    classified_confidence=confidence,
                )
            )

        return results

    def add_feedback(
        self,
        signal: LogSignal,
        correct_category: FailureCategory,
        batch_size: int = FEEDBACK_BATCH_SIZE,
    ) -> None:
        """
        Queue a corrected label for incremental learning.

        Feedback is accumulated until *batch_size* samples are pending, at
        which point the index is updated and persisted in one batch operation.

        Args:
            signal:           The signal that was misclassified or confirmed.
            correct_category: The ground-truth (or confirmed) category.
            batch_size:       How many pending samples trigger a batch update.
        """
        text = self._extract_text(signal)

        with self._lock:
            self._pending_texts.append(text)
            self._pending_labels.append(correct_category)

            if len(self._pending_texts) >= batch_size:
                self._apply_feedback_batch()

    def _apply_feedback_batch(self) -> None:
        """Flush the pending feedback queue into the FAISS index and persist."""
        if not self._pending_texts or not self._is_trained:
            return

        embeddings = embedding_obj.embed_batch(text=self._pending_texts)

        self.index.add(embeddings)
        self._training_labels.extend(self._pending_labels)

        logger.info(
            "Added %d feedback examples (total: %d).",
            len(self._pending_texts),
            len(self._training_labels),
        )

        self._pending_texts.clear()
        self._pending_labels.clear()

        self.save()

    def save(self) -> None:
        """Persist the classifier metadata and FAISS index to disk."""
        os.makedirs(os.path.dirname(self._model_path), exist_ok=True)

        with open(self._model_path, "wb") as fh:
            pickle.dump(
                {
                    "training_labels": self._training_labels,
                    "dimension": self.dimension,
                    "k_neighbors": self.k_neighbors,
                },
                fh,
            )

        if self.index:
            faiss.write_index(self.index, self._index_path)

    def _try_load(self) -> None:
        """Load classifier from disk; bootstrap from synthetic data if absent."""
        if not os.path.exists(self._model_path):
            logger.info("No model file found at '%s' — bootstrapping from synthetic data.", self._model_path)
            from analyzer.classifiers.training.synthetic_data_generator import generate

            dataset = generate()
            self.train(dataset)
            self.save()
            return

        try:
            with open(self._model_path, "rb") as fh:
                data = pickle.load(fh)

            self._training_labels = data["training_labels"]
            self.dimension = data["dimension"]
            self.k_neighbors = data.get("k_neighbors", 3)

            if os.path.exists(self._index_path):
                self.index = faiss.read_index(self._index_path)
                self._is_trained = True
                logger.info(
                    "SemanticClassifier loaded with %d samples.",
                    len(self._training_labels),
                )
        except Exception as e:
            logger.exception("Model load failed: %s", e)

    def _extract_text(self, signal: LogSignal) -> str:
        """
        Build a normalised text representation of a log signal for embedding.

        Combines the error line, a truncated post-context, and a short
        pre-context, each individually normalised.

        Args:
            signal: The log signal to convert.

        Returns:
            A normalised, space-joined string suitable for the embedding API.
        """
        parts = []

        if signal.error_line:
            parts.append(self._clean(signal.error_line))

        if signal.post_content:
            parts.append(self._clean(signal.post_content[:200]))

        if signal.pre_content:
            parts.append(self._clean(signal.pre_content[:100]))

        return " ".join(parts)

    @staticmethod
    def _clean(text: str) -> str:
        return text_norm_obj.normalize_for_embedding(text=text)